package ensambladorasony2;

import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

import static ensambladorasony2.Const.*;
import static ensambladorasony2.EnsambladoraSony2.*;

public class GUI_Simulacion extends javax.swing.JFrame {
    
    private final JFileChooser fileChooser;
    
    
    public GUI_Simulacion() {
        initComponents();
    
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("./"));
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_simulacion = new javax.swing.JButton();
        fabricas = new javax.swing.JTabbedPane();
        panel_fabrica1 = new javax.swing.JPanel();
        plots = new javax.swing.JTabbedPane();
        plt_costo = new javax.swing.JPanel();
        plt_ingreso = new javax.swing.JPanel();
        plt_ganancia = new javax.swing.JPanel();
        lb_gerente = new javax.swing.JLabel();
        menos_pant = new javax.swing.JButton();
        menos_cam = new javax.swing.JButton();
        lb_jefe_estado = new javax.swing.JLabel();
        lb_titulo_profit = new javax.swing.JLabel();
        lb_prod_cam = new javax.swing.JLabel();
        menos_pin = new javax.swing.JButton();
        lb_titulo_gerente = new javax.swing.JLabel();
        lb_titulo_dia = new javax.swing.JLabel();
        lb_titulo_botones = new javax.swing.JLabel();
        lb_prod_pant = new javax.swing.JLabel();
        lb_jefe_pago = new javax.swing.JLabel();
        lb_pantallas = new javax.swing.JLabel();
        lb_ingreso = new javax.swing.JLabel();
        lb_costo = new javax.swing.JLabel();
        lb_prod_pin = new javax.swing.JLabel();
        mas_ens = new javax.swing.JButton();
        mas_boton = new javax.swing.JButton();
        lb_titulo_prod_botones = new javax.swing.JLabel();
        lb_titulo_prod_pin = new javax.swing.JLabel();
        lb_prod_botones = new javax.swing.JLabel();
        menos_ens = new javax.swing.JButton();
        lb_titulo_prod_pant = new javax.swing.JLabel();
        menos_boton = new javax.swing.JButton();
        lb_deployed = new javax.swing.JLabel();
        lb_titulo_costo = new javax.swing.JLabel();
        lb_titulo_camaras = new javax.swing.JLabel();
        mas_cam = new javax.swing.JButton();
        lb_botones = new javax.swing.JLabel();
        lb_dia = new javax.swing.JLabel();
        lb_titulo_pantallas = new javax.swing.JLabel();
        lb_titulo_prod_cam = new javax.swing.JLabel();
        lb_pines = new javax.swing.JLabel();
        lb_titulo_ingreso = new javax.swing.JLabel();
        lb_celulares = new javax.swing.JLabel();
        lb_profit = new javax.swing.JLabel();
        lb_titulo_deployed = new javax.swing.JLabel();
        lb_titulo_celulares = new javax.swing.JLabel();
        lb_ens = new javax.swing.JLabel();
        mas_pant = new javax.swing.JButton();
        lb_camaras = new javax.swing.JLabel();
        lb_titulo_ens = new javax.swing.JLabel();
        mas_pin = new javax.swing.JButton();
        lb_titulo_pines = new javax.swing.JLabel();
        lb_titulo_jefe = new javax.swing.JLabel();
        btn_archivo = new javax.swing.JButton();
        panel_fabrica2 = new javax.swing.JPanel();
        lb_gerente1 = new javax.swing.JLabel();
        menos_pant1 = new javax.swing.JButton();
        menos_cam1 = new javax.swing.JButton();
        lb_jefe_estado1 = new javax.swing.JLabel();
        lb_titulo_profit1 = new javax.swing.JLabel();
        lb_prod_cam1 = new javax.swing.JLabel();
        menos_pin1 = new javax.swing.JButton();
        lb_titulo_gerente1 = new javax.swing.JLabel();
        lb_titulo_dia1 = new javax.swing.JLabel();
        lb_titulo_botones1 = new javax.swing.JLabel();
        lb_prod_pant1 = new javax.swing.JLabel();
        lb_jefe_pago1 = new javax.swing.JLabel();
        lb_pantallas1 = new javax.swing.JLabel();
        lb_ingreso1 = new javax.swing.JLabel();
        lb_costo1 = new javax.swing.JLabel();
        lb_prod_pin1 = new javax.swing.JLabel();
        mas_ens1 = new javax.swing.JButton();
        mas_boton1 = new javax.swing.JButton();
        lb_titulo_prod_botones1 = new javax.swing.JLabel();
        lb_titulo_prod_pin1 = new javax.swing.JLabel();
        lb_prod_botones1 = new javax.swing.JLabel();
        menos_ens1 = new javax.swing.JButton();
        lb_titulo_prod_pant1 = new javax.swing.JLabel();
        menos_boton1 = new javax.swing.JButton();
        lb_deployed1 = new javax.swing.JLabel();
        lb_titulo_costo1 = new javax.swing.JLabel();
        lb_titulo_camaras1 = new javax.swing.JLabel();
        mas_cam1 = new javax.swing.JButton();
        lb_botones1 = new javax.swing.JLabel();
        lb_dia1 = new javax.swing.JLabel();
        lb_titulo_pantallas1 = new javax.swing.JLabel();
        lb_titulo_prod_cam1 = new javax.swing.JLabel();
        lb_pines1 = new javax.swing.JLabel();
        lb_titulo_ingreso1 = new javax.swing.JLabel();
        lb_celulares1 = new javax.swing.JLabel();
        lb_profit1 = new javax.swing.JLabel();
        lb_titulo_deployed1 = new javax.swing.JLabel();
        lb_titulo_celulares1 = new javax.swing.JLabel();
        lb_ens1 = new javax.swing.JLabel();
        mas_pant1 = new javax.swing.JButton();
        lb_camaras1 = new javax.swing.JLabel();
        lb_titulo_ens1 = new javax.swing.JLabel();
        mas_pin1 = new javax.swing.JButton();
        lb_titulo_pines1 = new javax.swing.JLabel();
        lb_titulo_jefe1 = new javax.swing.JLabel();
        plots1 = new javax.swing.JTabbedPane();
        plt_ingreso1 = new javax.swing.JPanel();
        plt_ganancia1 = new javax.swing.JPanel();
        plt_costo1 = new javax.swing.JPanel();
        btn_archivo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_simulacion.setText("Empezar Simulación");
        btn_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simulacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plt_costoLayout = new javax.swing.GroupLayout(plt_costo);
        plt_costo.setLayout(plt_costoLayout);
        plt_costoLayout.setHorizontalGroup(
            plt_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        plt_costoLayout.setVerticalGroup(
            plt_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        plots.addTab("Costo", plt_costo);

        javax.swing.GroupLayout plt_ingresoLayout = new javax.swing.GroupLayout(plt_ingreso);
        plt_ingreso.setLayout(plt_ingresoLayout);
        plt_ingresoLayout.setHorizontalGroup(
            plt_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        plt_ingresoLayout.setVerticalGroup(
            plt_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        plots.addTab("Ingreso", plt_ingreso);

        javax.swing.GroupLayout plt_gananciaLayout = new javax.swing.GroupLayout(plt_ganancia);
        plt_ganancia.setLayout(plt_gananciaLayout);
        plt_gananciaLayout.setHorizontalGroup(
            plt_gananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        plt_gananciaLayout.setVerticalGroup(
            plt_gananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        plots.addTab("Ganancia", plt_ganancia);

        lb_gerente.setText("_");

        menos_pant.setText("-");
        menos_pant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_pantActionPerformed(evt);
            }
        });

        menos_cam.setText("-");
        menos_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_camActionPerformed(evt);
            }
        });

        lb_jefe_estado.setText("_");

        lb_titulo_profit.setText("Ganancias:");

        lb_prod_cam.setText("_");

        menos_pin.setText("-");
        menos_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_pinActionPerformed(evt);
            }
        });

        lb_titulo_gerente.setText("Estado del Gerente:");

        lb_titulo_dia.setText("Dias para Lanzamiento:");

        lb_titulo_botones.setText("Botones:");

        lb_prod_pant.setText("_");

        lb_jefe_pago.setText("_");

        lb_pantallas.setText("_");

        lb_ingreso.setText("_");

        lb_costo.setText("_");

        lb_prod_pin.setText("_");

        mas_ens.setText("+");
        mas_ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_ensActionPerformed(evt);
            }
        });

        mas_boton.setText("+");
        mas_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_botonActionPerformed(evt);
            }
        });

        lb_titulo_prod_botones.setText("Productores de Botones:");

        lb_titulo_prod_pin.setText("Productores de Pines de Carga:");

        lb_prod_botones.setText("_");

        menos_ens.setText("-");
        menos_ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_ensActionPerformed(evt);
            }
        });

        lb_titulo_prod_pant.setText("Productores de Pantallas:");

        menos_boton.setText("-");
        menos_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_botonActionPerformed(evt);
            }
        });

        lb_deployed.setText("_");

        lb_titulo_costo.setText("Costo:");

        lb_titulo_camaras.setText("Camaras:");

        mas_cam.setText("+");
        mas_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_camActionPerformed(evt);
            }
        });

        lb_botones.setText("_");

        lb_dia.setText("_");

        lb_titulo_pantallas.setText("Pantallas:");

        lb_titulo_prod_cam.setText("Productores de Cámaras:");

        lb_pines.setText("_");

        lb_titulo_ingreso.setText("Ingreso Bruto:");

        lb_celulares.setText("_");

        lb_profit.setText("_");

        lb_titulo_deployed.setText("Celulares Lanzados:");

        lb_titulo_celulares.setText("Celulares:");

        lb_ens.setText("_");

        mas_pant.setText("+");
        mas_pant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_pantActionPerformed(evt);
            }
        });

        lb_camaras.setText("_");

        lb_titulo_ens.setText("Ensambladores:");

        mas_pin.setText("+");
        mas_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_pinActionPerformed(evt);
            }
        });

        lb_titulo_pines.setText("Pines de Carga:");

        lb_titulo_jefe.setText("Jefe:");

        btn_archivo.setText("Abrir Archivo CSV");
        btn_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_archivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fabrica1Layout = new javax.swing.GroupLayout(panel_fabrica1);
        panel_fabrica1.setLayout(panel_fabrica1Layout);
        panel_fabrica1Layout.setHorizontalGroup(
            panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fabrica1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plots)
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_prod_botones)
                                .addComponent(lb_titulo_prod_botones)
                                .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                    .addComponent(mas_boton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(menos_boton))
                                .addComponent(lb_prod_cam)
                                .addComponent(lb_titulo_prod_cam)
                                .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                    .addComponent(mas_cam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(menos_cam))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fabrica1Layout.createSequentialGroup()
                                    .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_botones)
                                        .addComponent(lb_titulo_botones))
                                    .addGap(33, 33, 33)
                                    .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_pantallas)
                                        .addComponent(lb_titulo_pantallas)
                                        .addComponent(lb_ingreso)
                                        .addComponent(lb_titulo_ingreso))))
                            .addComponent(lb_costo)
                            .addComponent(lb_titulo_costo))
                        .addGap(34, 34, 34)
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_deployed)
                                    .addComponent(lb_titulo_deployed))
                                .addGap(18, 18, 18)
                                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_profit)
                                    .addComponent(lb_titulo_profit))
                                .addGap(18, 18, 18)
                                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_dia)
                                    .addComponent(lb_titulo_dia)))
                            .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_prod_pin)
                                    .addComponent(lb_titulo_prod_pin)
                                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                        .addComponent(mas_pin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menos_pin))
                                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                        .addComponent(mas_pant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menos_pant))
                                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_camaras)
                                            .addComponent(lb_titulo_camaras))
                                        .addGap(31, 31, 31)
                                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_pines)
                                            .addComponent(lb_titulo_pines)))
                                    .addComponent(lb_titulo_prod_pant)
                                    .addComponent(lb_prod_pant))
                                .addGap(34, 34, 34)
                                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lb_gerente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lb_titulo_gerente, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(lb_ens)
                                            .addComponent(lb_titulo_ens)
                                            .addComponent(lb_celulares)
                                            .addComponent(lb_titulo_celulares)
                                            .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                                .addComponent(mas_ens)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(menos_ens)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                                        .addComponent(lb_titulo_jefe)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_jefe_pago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lb_jefe_estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(btn_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_fabrica1Layout.setVerticalGroup(
            panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fabrica1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_prod_botones)
                        .addGap(1, 1, 1)
                        .addComponent(lb_prod_botones)
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_boton)
                            .addComponent(menos_boton)))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_prod_pin)
                        .addGap(1, 1, 1)
                        .addComponent(lb_prod_pin)
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_pin)
                            .addComponent(menos_pin)))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_ens)
                        .addGap(1, 1, 1)
                        .addComponent(lb_ens)
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_ens)
                            .addComponent(menos_ens))))
                .addGap(18, 18, 18)
                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_prod_cam)
                        .addGap(1, 1, 1)
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_prod_cam)
                            .addComponent(lb_prod_pant))
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_cam)
                            .addComponent(menos_cam)
                            .addComponent(mas_pant)
                            .addComponent(menos_pant)))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_titulo_prod_pant)
                            .addComponent(lb_jefe_pago)
                            .addComponent(lb_titulo_jefe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jefe_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_titulo_gerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_gerente)))
                .addGap(56, 56, 56)
                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_botones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_botones))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_camaras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_camaras))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_pines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_pines))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_pantallas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_pantallas))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_celulares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_celulares)))
                .addGap(18, 18, 18)
                .addGroup(panel_fabrica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_costo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_costo))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_ingreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_ingreso))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_deployed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_deployed))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_profit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_profit))
                    .addGroup(panel_fabrica1Layout.createSequentialGroup()
                        .addComponent(lb_titulo_dia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_dia)))
                .addGap(31, 31, 31)
                .addComponent(btn_archivo)
                .addGap(18, 18, 18)
                .addComponent(plots, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fabricas.addTab("Fabrica 1", panel_fabrica1);

        lb_gerente1.setText("_");

        menos_pant1.setText("-");
        menos_pant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_pant1ActionPerformed(evt);
            }
        });

        menos_cam1.setText("-");
        menos_cam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_cam1ActionPerformed(evt);
            }
        });

        lb_jefe_estado1.setText("_");

        lb_titulo_profit1.setText("Ganancias:");

        lb_prod_cam1.setText("_");

        menos_pin1.setText("-");
        menos_pin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_pin1ActionPerformed(evt);
            }
        });

        lb_titulo_gerente1.setText("Estado del Gerente:");

        lb_titulo_dia1.setText("Dias para Lanzamiento:");

        lb_titulo_botones1.setText("Botones:");

        lb_prod_pant1.setText("_");

        lb_jefe_pago1.setText("_");

        lb_pantallas1.setText("_");

        lb_ingreso1.setText("_");

        lb_costo1.setText("_");

        lb_prod_pin1.setText("_");

        mas_ens1.setText("+");
        mas_ens1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_ens1ActionPerformed(evt);
            }
        });

        mas_boton1.setText("+");
        mas_boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_boton1ActionPerformed(evt);
            }
        });

        lb_titulo_prod_botones1.setText("Productores de Botones:");

        lb_titulo_prod_pin1.setText("Productores de Pines de Carga:");

        lb_prod_botones1.setText("_");

        menos_ens1.setText("-");
        menos_ens1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_ens1ActionPerformed(evt);
            }
        });

        lb_titulo_prod_pant1.setText("Productores de Pantallas:");

        menos_boton1.setText("-");
        menos_boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_boton1ActionPerformed(evt);
            }
        });

        lb_deployed1.setText("_");

        lb_titulo_costo1.setText("Costo:");

        lb_titulo_camaras1.setText("Camaras:");

        mas_cam1.setText("+");
        mas_cam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_cam1ActionPerformed(evt);
            }
        });

        lb_botones1.setText("_");

        lb_dia1.setText("_");

        lb_titulo_pantallas1.setText("Pantallas:");

        lb_titulo_prod_cam1.setText("Productores de Cámaras:");

        lb_pines1.setText("_");

        lb_titulo_ingreso1.setText("Ingreso Bruto:");

        lb_celulares1.setText("_");

        lb_profit1.setText("_");

        lb_titulo_deployed1.setText("Celulares Lanzados:");

        lb_titulo_celulares1.setText("Celulares:");

        lb_ens1.setText("_");

        mas_pant1.setText("+");
        mas_pant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_pant1ActionPerformed(evt);
            }
        });

        lb_camaras1.setText("_");

        lb_titulo_ens1.setText("Ensambladores:");

        mas_pin1.setText("+");
        mas_pin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_pin1ActionPerformed(evt);
            }
        });

        lb_titulo_pines1.setText("Pines de Carga:");

        lb_titulo_jefe1.setText("Jefe:");

        javax.swing.GroupLayout plt_ingreso1Layout = new javax.swing.GroupLayout(plt_ingreso1);
        plt_ingreso1.setLayout(plt_ingreso1Layout);
        plt_ingreso1Layout.setHorizontalGroup(
            plt_ingreso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        plt_ingreso1Layout.setVerticalGroup(
            plt_ingreso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        plots1.addTab("Ingreso", plt_ingreso1);

        javax.swing.GroupLayout plt_ganancia1Layout = new javax.swing.GroupLayout(plt_ganancia1);
        plt_ganancia1.setLayout(plt_ganancia1Layout);
        plt_ganancia1Layout.setHorizontalGroup(
            plt_ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        plt_ganancia1Layout.setVerticalGroup(
            plt_ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        plots1.addTab("Ganancia", plt_ganancia1);

        javax.swing.GroupLayout plt_costo1Layout = new javax.swing.GroupLayout(plt_costo1);
        plt_costo1.setLayout(plt_costo1Layout);
        plt_costo1Layout.setHorizontalGroup(
            plt_costo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        plt_costo1Layout.setVerticalGroup(
            plt_costo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        plots1.addTab("Costo", plt_costo1);

        btn_archivo1.setText("Abrir Archivo CSV");
        btn_archivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_archivo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fabrica2Layout = new javax.swing.GroupLayout(panel_fabrica2);
        panel_fabrica2.setLayout(panel_fabrica2Layout);
        panel_fabrica2Layout.setHorizontalGroup(
            panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fabrica2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_prod_botones1)
                                .addComponent(lb_titulo_prod_botones1)
                                .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                    .addComponent(mas_boton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(menos_boton1))
                                .addComponent(lb_prod_cam1)
                                .addComponent(lb_titulo_prod_cam1)
                                .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                    .addComponent(mas_cam1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(menos_cam1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fabrica2Layout.createSequentialGroup()
                                    .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_botones1)
                                        .addComponent(lb_titulo_botones1))
                                    .addGap(33, 33, 33)
                                    .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_pantallas1)
                                        .addComponent(lb_titulo_pantallas1)
                                        .addComponent(lb_ingreso1)
                                        .addComponent(lb_titulo_ingreso1))))
                            .addComponent(lb_costo1)
                            .addComponent(lb_titulo_costo1))
                        .addGap(34, 34, 34)
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_deployed1)
                                    .addComponent(lb_titulo_deployed1))
                                .addGap(18, 18, 18)
                                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_profit1)
                                    .addComponent(lb_titulo_profit1))
                                .addGap(18, 18, 18)
                                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_dia1)
                                    .addComponent(lb_titulo_dia1)))
                            .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_prod_pin1)
                                    .addComponent(lb_titulo_prod_pin1)
                                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                        .addComponent(mas_pin1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menos_pin1))
                                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                        .addComponent(mas_pant1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menos_pant1))
                                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_camaras1)
                                            .addComponent(lb_titulo_camaras1))
                                        .addGap(31, 31, 31)
                                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_pines1)
                                            .addComponent(lb_titulo_pines1)))
                                    .addComponent(lb_titulo_prod_pant1)
                                    .addComponent(lb_prod_pant1))
                                .addGap(34, 34, 34)
                                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lb_gerente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lb_titulo_gerente1, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(lb_ens1)
                                            .addComponent(lb_titulo_ens1)
                                            .addComponent(lb_celulares1)
                                            .addComponent(lb_titulo_celulares1)
                                            .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                                .addComponent(mas_ens1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(menos_ens1)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                                        .addComponent(lb_titulo_jefe1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_jefe_pago1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lb_jefe_estado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(btn_archivo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plots1))
                .addContainerGap())
        );
        panel_fabrica2Layout.setVerticalGroup(
            panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fabrica2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_prod_botones1)
                        .addGap(1, 1, 1)
                        .addComponent(lb_prod_botones1)
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_boton1)
                            .addComponent(menos_boton1)))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_prod_pin1)
                        .addGap(1, 1, 1)
                        .addComponent(lb_prod_pin1)
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_pin1)
                            .addComponent(menos_pin1)))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_ens1)
                        .addGap(1, 1, 1)
                        .addComponent(lb_ens1)
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_ens1)
                            .addComponent(menos_ens1))))
                .addGap(18, 18, 18)
                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_prod_cam1)
                        .addGap(1, 1, 1)
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_prod_cam1)
                            .addComponent(lb_prod_pant1))
                        .addGap(3, 3, 3)
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mas_cam1)
                            .addComponent(menos_cam1)
                            .addComponent(mas_pant1)
                            .addComponent(menos_pant1)))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_titulo_prod_pant1)
                            .addComponent(lb_jefe_pago1)
                            .addComponent(lb_titulo_jefe1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jefe_estado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_titulo_gerente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_gerente1)))
                .addGap(56, 56, 56)
                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_botones1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_botones1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_camaras1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_camaras1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_pines1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_pines1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_pantallas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_pantallas1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_celulares1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_celulares1)))
                .addGap(18, 18, 18)
                .addGroup(panel_fabrica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_costo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_costo1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_ingreso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_ingreso1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_deployed1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_deployed1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_profit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_profit1))
                    .addGroup(panel_fabrica2Layout.createSequentialGroup()
                        .addComponent(lb_titulo_dia1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_dia1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btn_archivo1)
                .addGap(18, 18, 18)
                .addComponent(plots1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fabricas.addTab("Fabrica 2", panel_fabrica2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fabricas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_simulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(fabricas, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_simulacion)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menos_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_botonActionPerformed
        // TODO add your handling code here:
        if( f1.getCantidadProductor(BOTON) <= 1 )
            return;
        f1.removeProductor(BOTON);
        set_prod_botones( f1.getCantidadProductor(BOTON), 1 );
    }//GEN-LAST:event_menos_botonActionPerformed

    private void menos_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_camActionPerformed
        // TODO add your handling code here:
        if( f1.getCantidadProductor(CAMARA) <= 1 )
            return;
        f1.removeProductor(CAMARA);
        set_prod_cam( f1.getCantidadProductor(CAMARA), 1 );
    }//GEN-LAST:event_menos_camActionPerformed

    private void mas_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_camActionPerformed
        // TODO add your handling code here:
        f1.addProductor(CAMARA);
        set_prod_cam( f1.getCantidadProductor(CAMARA), 1 );
    }//GEN-LAST:event_mas_camActionPerformed

    private void mas_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_pinActionPerformed
        // TODO add your handling code here:
        f1.addProductor(PIN);
        set_prod_pin( f1.getCantidadProductor(PIN), 1 );
    }//GEN-LAST:event_mas_pinActionPerformed

    private void menos_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_pinActionPerformed
        // TODO add your handling code here:
        if( f1.getCantidadProductor(PIN) <= 1 )
            return;
        f1.removeProductor(PIN);
        set_prod_pin( f1.getCantidadProductor(PIN), 1 );
    }//GEN-LAST:event_menos_pinActionPerformed

    private void mas_pantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_pantActionPerformed
        // TODO add your handling code here:
        f1.addProductor(PANTALLA);
        set_prod_pantallas( f1.getCantidadProductor(PANTALLA), 1 );
    }//GEN-LAST:event_mas_pantActionPerformed

    private void menos_pantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_pantActionPerformed
        // TODO add your handling code here:
        if( f1.getCantidadProductor(PANTALLA) <= 1 )
            return;
        f1.removeProductor(PANTALLA);
        set_prod_pantallas( f1.getCantidadProductor(PANTALLA), 1 );
    }//GEN-LAST:event_menos_pantActionPerformed

    private void mas_ensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_ensActionPerformed
        // TODO add your handling code here:
        f1.addEnsamblador();
        set_ensambladores( f1.getCantidadEnsambladores(), 1 );
    }//GEN-LAST:event_mas_ensActionPerformed

    private void menos_ensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_ensActionPerformed
        // TODO add your handling code here:
        if( f1.getCantidadEnsambladores() <= 1 )
            return;
        f1.removeEnsamblador();
        set_ensambladores( f1.getCantidadEnsambladores(), 1 );
    }//GEN-LAST:event_menos_ensActionPerformed

    private void btn_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simulacionActionPerformed
        // TODO add your handling code here:
        if( activo ){
            detenerSimulacion();
            btn_simulacion.setText("Empezar Simulacion");
        }else{
            empezarSimulacion();
            btn_simulacion.setText("Detener Simulacion");
        }
    }//GEN-LAST:event_btn_simulacionActionPerformed

    private void mas_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_botonActionPerformed
        // TODO add your handling code here:
        f1.addProductor(BOTON);
        set_prod_botones( f1.getCantidadProductor(BOTON), 1 );
    }//GEN-LAST:event_mas_botonActionPerformed

    private void btn_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_archivoActionPerformed
        // TODO add your handling code here:
        int ret = fileChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            
            try{
                Scanner sc = new Scanner( fileChooser.getSelectedFile() );
                sc.nextLine();
                String[] config = sc.nextLine().split(",");
                
                f1.setInit(
                        Integer.parseInt( config[0] ),
                        Integer.parseInt( config[1] ),
                        Integer.parseInt( config[3] ),
                        Integer.parseInt( config[2] ),
                        Integer.parseInt( config[4] ));
                
                
                System.out.println("Archivo Cargado");
                
                gui.set_prod_botones(Integer.parseInt( config[0] ),1 );
                gui.set_prod_cam(Integer.parseInt( config[1] ),1);
                gui.set_prod_pin(Integer.parseInt( config[2] ),1 );
                gui.set_prod_pantallas(Integer.parseInt( config[3] ),1 );
                gui.set_ensambladores(Integer.parseInt( config[4] ),1 );
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btn_archivoActionPerformed

    private void menos_pant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_pant1ActionPerformed
        // TODO add your handling code here:
        if( f2.getCantidadProductor(PANTALLA) <= 1 )
            return;
        f2.removeProductor(PANTALLA);
        set_prod_pantallas( f2.getCantidadProductor(PANTALLA), 2 );
    }//GEN-LAST:event_menos_pant1ActionPerformed

    private void menos_cam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_cam1ActionPerformed
        // TODO add your handling code here:
        if( f2.getCantidadProductor(CAMARA) <= 1 )
            return;
        f2.removeProductor(CAMARA);
        set_prod_cam( f2.getCantidadProductor(CAMARA), 2 );
    }//GEN-LAST:event_menos_cam1ActionPerformed

    private void menos_pin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_pin1ActionPerformed
        // TODO add your handling code here:
        if( f2.getCantidadProductor(PIN) <= 1 )
            return;
        f2.removeProductor(PIN);
        set_prod_pin( f2.getCantidadProductor(PIN), 2 );
    }//GEN-LAST:event_menos_pin1ActionPerformed

    private void mas_ens1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_ens1ActionPerformed
        // TODO add your handling code here:
        f2.addEnsamblador();
        set_ensambladores( f2.getCantidadEnsambladores(), 2 );
    }//GEN-LAST:event_mas_ens1ActionPerformed

    private void mas_boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_boton1ActionPerformed
        // TODO add your handling code here:
        f2.addProductor(BOTON);
        set_prod_botones( f2.getCantidadProductor(BOTON), 2 );
    }//GEN-LAST:event_mas_boton1ActionPerformed

    private void menos_ens1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_ens1ActionPerformed
        // TODO add your handling code here:
        if( f2.getCantidadEnsambladores() <= 1 )
            return;
        f2.removeEnsamblador();
        set_ensambladores( f2.getCantidadEnsambladores(), 2 );
    }//GEN-LAST:event_menos_ens1ActionPerformed

    private void menos_boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_boton1ActionPerformed
        // TODO add your handling code here:
        if( f2.getCantidadProductor(BOTON) <= 1 )
            return;
        f2.removeProductor(BOTON);
        set_prod_botones( f2.getCantidadProductor(BOTON), 2 );
    }//GEN-LAST:event_menos_boton1ActionPerformed

    private void mas_cam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_cam1ActionPerformed
        // TODO add your handling code here:
        f2.addProductor(CAMARA);
        set_prod_cam( f2.getCantidadProductor(CAMARA), 2 );
    }//GEN-LAST:event_mas_cam1ActionPerformed

    private void mas_pant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_pant1ActionPerformed
        // TODO add your handling code here:
        f2.addProductor(PANTALLA);
        set_prod_pantallas( f2.getCantidadProductor(PANTALLA), 2 );
    }//GEN-LAST:event_mas_pant1ActionPerformed

    private void mas_pin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_pin1ActionPerformed
        // TODO add your handling code here:
        f2.addProductor(PIN);
        set_prod_pin( f2.getCantidadProductor(PIN), 2 );
    }//GEN-LAST:event_mas_pin1ActionPerformed

    private void btn_archivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_archivo1ActionPerformed
        // TODO add your handling code here:
        int ret = fileChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            
            try{
                Scanner sc = new Scanner( fileChooser.getSelectedFile() );
                sc.nextLine();
                String[] config = sc.nextLine().split(",");
                
                f2.setInit(
                        Integer.parseInt( config[0] ),
                        Integer.parseInt( config[1] ),
                        Integer.parseInt( config[3] ),
                        Integer.parseInt( config[2] ),
                        Integer.parseInt( config[4] ));
                
                
                System.out.println("Archivo Cargado");
                
                gui.set_prod_botones( Integer.parseInt( config[0] ),2 );
                gui.set_prod_cam( Integer.parseInt( config[1] ),2);
                gui.set_prod_pin( Integer.parseInt( config[2] ),2 );
                gui.set_prod_pantallas( Integer.parseInt( config[3] ),2 );
                gui.set_ensambladores(Integer.parseInt( config[4] ),2 );
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_archivo1ActionPerformed

    public void set_prod_botones(int n, int f){
        if(f == 1)
            lb_prod_botones.setText( ""+n );
        else
            lb_prod_botones1.setText(""+n);
    }
    
    public void set_prod_pantallas(int n, int f){
        if(f == 1)
            lb_prod_pant.setText( ""+n );
        else
            lb_prod_pant1.setText(""+n);
        
    }
    
    public void set_prod_pin(int n, int f){
        if(f == 1)
            lb_prod_pin.setText( ""+n );
        else
            lb_prod_pin1.setText(""+n);
    }
    
    public void set_prod_cam(int n, int f){
        if(f == 1)
            lb_prod_cam.setText( ""+n );
        else
            lb_prod_cam1.setText(""+n);
    }
    
    public void set_pantallas(int n, int f){
        if(f == 1)
            lb_pantallas.setText( ""+n );
        else
            lb_pantallas1.setText(""+n);
    }
    
    public void set_ensambladores(int n, int f){
        if(f == 1)
            lb_ens.setText( ""+n );
        else
            lb_ens1.setText(""+n);
    }
    
    public void set_dia(int n, int f){
        if(f == 1)
            lb_dia.setText( ""+n );
        else
            lb_dia1.setText(""+n);
    }
    
    public void set_botones(int n, int f){
        if(f == 1)
            lb_botones.setText( ""+n );
        else
            lb_botones1.setText(""+n);
    }
    
    public void set_pines(int n, int f){
        if(f == 1)
            lb_pines.setText( ""+n );
        else
            lb_pines1.setText(""+n);
    }
    
    public void set_camaras(int n, int f){
        if(f == 1)
            lb_camaras.setText( ""+n );
        else
            lb_camaras1.setText(""+n);
    }
    
    public void set_costo(int n, int f){
        if(f == 1)
            lb_costo.setText( ""+n+"$");
        else
            lb_costo1.setText(""+n+"$");
    }
    
    public void set_ingreso_bruto(int n, int f){
        if(f == 1)
            lb_ingreso.setText( ""+n+"$");
        else
            lb_ingreso1.setText(""+n+"$");
    }
    
    public void set_ganancia(int n, int f){
        if(f == 1)
            lb_profit.setText( ""+n+"$");
        else
            lb_profit1.setText(""+n+"$");
    }
    
    public void set_deployed(int n, int f){
        if(f == 1)
            lb_deployed.setText( ""+n );
        else
            lb_deployed1.setText(""+n);
    }
    
    public void set_pago_jefe(int n, int f){
        if(f == 1)
            lb_jefe_pago.setText( ""+n+"$");
        else
            lb_jefe_pago1.setText(""+n+"$");
    }
    
    public void set_estado_jefe(String str, int f){
        if(f == 1)
            lb_jefe_estado.setText( str );
        else
            lb_jefe_estado1.setText(str);
    }
    
    public void set_estado_gerente(String str, int f){
        if(f == 1)
            lb_gerente.setText( str );
        else
            lb_gerente1.setText(str);
    }
    
    public void set_celulares(int n, int f){
        if(f == 1)
            lb_celulares.setText( ""+n );
        else
            lb_celulares1.setText(""+n);
    }
    
    public JPanel get_plt_costo(int f){
        if(f == 1)
            return plt_costo;
        else
            return plt_costo1;
    }
    
    public JPanel get_plt_ingreso(int f){
        if(f == 1)
            return plt_ingreso;
        else
            return plt_ingreso1;
    }
    
    public JPanel get_plt_ganancia(int f){
        if(f == 1)
            return plt_ganancia;
        else
            return plt_ganancia1;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_Simulacion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_archivo;
    private javax.swing.JButton btn_archivo1;
    private javax.swing.JButton btn_simulacion;
    private javax.swing.JTabbedPane fabricas;
    private javax.swing.JLabel lb_botones;
    private javax.swing.JLabel lb_botones1;
    private javax.swing.JLabel lb_camaras;
    private javax.swing.JLabel lb_camaras1;
    private javax.swing.JLabel lb_celulares;
    private javax.swing.JLabel lb_celulares1;
    private javax.swing.JLabel lb_costo;
    private javax.swing.JLabel lb_costo1;
    private javax.swing.JLabel lb_deployed;
    private javax.swing.JLabel lb_deployed1;
    private javax.swing.JLabel lb_dia;
    private javax.swing.JLabel lb_dia1;
    private javax.swing.JLabel lb_ens;
    private javax.swing.JLabel lb_ens1;
    private javax.swing.JLabel lb_gerente;
    private javax.swing.JLabel lb_gerente1;
    private javax.swing.JLabel lb_ingreso;
    private javax.swing.JLabel lb_ingreso1;
    private javax.swing.JLabel lb_jefe_estado;
    private javax.swing.JLabel lb_jefe_estado1;
    private javax.swing.JLabel lb_jefe_pago;
    private javax.swing.JLabel lb_jefe_pago1;
    private javax.swing.JLabel lb_pantallas;
    private javax.swing.JLabel lb_pantallas1;
    private javax.swing.JLabel lb_pines;
    private javax.swing.JLabel lb_pines1;
    private javax.swing.JLabel lb_prod_botones;
    private javax.swing.JLabel lb_prod_botones1;
    private javax.swing.JLabel lb_prod_cam;
    private javax.swing.JLabel lb_prod_cam1;
    private javax.swing.JLabel lb_prod_pant;
    private javax.swing.JLabel lb_prod_pant1;
    private javax.swing.JLabel lb_prod_pin;
    private javax.swing.JLabel lb_prod_pin1;
    private javax.swing.JLabel lb_profit;
    private javax.swing.JLabel lb_profit1;
    private javax.swing.JLabel lb_titulo_botones;
    private javax.swing.JLabel lb_titulo_botones1;
    private javax.swing.JLabel lb_titulo_camaras;
    private javax.swing.JLabel lb_titulo_camaras1;
    private javax.swing.JLabel lb_titulo_celulares;
    private javax.swing.JLabel lb_titulo_celulares1;
    private javax.swing.JLabel lb_titulo_costo;
    private javax.swing.JLabel lb_titulo_costo1;
    private javax.swing.JLabel lb_titulo_deployed;
    private javax.swing.JLabel lb_titulo_deployed1;
    private javax.swing.JLabel lb_titulo_dia;
    private javax.swing.JLabel lb_titulo_dia1;
    private javax.swing.JLabel lb_titulo_ens;
    private javax.swing.JLabel lb_titulo_ens1;
    private javax.swing.JLabel lb_titulo_gerente;
    private javax.swing.JLabel lb_titulo_gerente1;
    private javax.swing.JLabel lb_titulo_ingreso;
    private javax.swing.JLabel lb_titulo_ingreso1;
    private javax.swing.JLabel lb_titulo_jefe;
    private javax.swing.JLabel lb_titulo_jefe1;
    private javax.swing.JLabel lb_titulo_pantallas;
    private javax.swing.JLabel lb_titulo_pantallas1;
    private javax.swing.JLabel lb_titulo_pines;
    private javax.swing.JLabel lb_titulo_pines1;
    private javax.swing.JLabel lb_titulo_prod_botones;
    private javax.swing.JLabel lb_titulo_prod_botones1;
    private javax.swing.JLabel lb_titulo_prod_cam;
    private javax.swing.JLabel lb_titulo_prod_cam1;
    private javax.swing.JLabel lb_titulo_prod_pant;
    private javax.swing.JLabel lb_titulo_prod_pant1;
    private javax.swing.JLabel lb_titulo_prod_pin;
    private javax.swing.JLabel lb_titulo_prod_pin1;
    private javax.swing.JLabel lb_titulo_profit;
    private javax.swing.JLabel lb_titulo_profit1;
    private javax.swing.JButton mas_boton;
    private javax.swing.JButton mas_boton1;
    private javax.swing.JButton mas_cam;
    private javax.swing.JButton mas_cam1;
    private javax.swing.JButton mas_ens;
    private javax.swing.JButton mas_ens1;
    private javax.swing.JButton mas_pant;
    private javax.swing.JButton mas_pant1;
    private javax.swing.JButton mas_pin;
    private javax.swing.JButton mas_pin1;
    private javax.swing.JButton menos_boton;
    private javax.swing.JButton menos_boton1;
    private javax.swing.JButton menos_cam;
    private javax.swing.JButton menos_cam1;
    private javax.swing.JButton menos_ens;
    private javax.swing.JButton menos_ens1;
    private javax.swing.JButton menos_pant;
    private javax.swing.JButton menos_pant1;
    private javax.swing.JButton menos_pin;
    private javax.swing.JButton menos_pin1;
    private javax.swing.JPanel panel_fabrica1;
    private javax.swing.JPanel panel_fabrica2;
    private javax.swing.JTabbedPane plots;
    private javax.swing.JTabbedPane plots1;
    private javax.swing.JPanel plt_costo;
    private javax.swing.JPanel plt_costo1;
    private javax.swing.JPanel plt_ganancia;
    private javax.swing.JPanel plt_ganancia1;
    private javax.swing.JPanel plt_ingreso;
    private javax.swing.JPanel plt_ingreso1;
    // End of variables declaration//GEN-END:variables
}
